import Head from 'next/head'
import Header from '../components/Header'
import Feed from '../components/Feed'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Insta-Clone</title>
        <meta name="Insta-Clone" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        {/* Feed */}
        <Feed />

        {/* Modal */}
        <section></section>
      </main>
    </div>
  )
}
