import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Insta-Clone</title>
        <meta name="Insta-Clone" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1 className="font-bold text-3xl text-red-500">Hello World</h1>
        </div>
      </main>
    </div>
  )
}
